#import <Foundation/Foundation.h>

@class NIMApiClient;

/**
* NimiqStats
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: 1.0.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


@protocol NIMApi <NSObject>

@property(readonly, nonatomic, strong) NIMApiClient *apiClient;

-(instancetype) initWithApiClient:(NIMApiClient *)apiClient;

-(void) setDefaultHeaderValue:(NSString*) value forKey:(NSString*)key;
-(NSString*) defaultHeaderForKey:(NSString*)key;

-(NSDictionary *)defaultHeaders;

@end
