#import <Foundation/Foundation.h>
#import "NIMData.h"
#import "NIMApi.h"

/**
* NimiqStats
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: 1.0.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/



@interface NIMDefaultApi: NSObject <NIMApi>

extern NSString* kNIMDefaultApiErrorDomain;
extern NSInteger kNIMDefaultApiMissingParamErrorCode;

-(instancetype) initWithApiClient:(NIMApiClient *)apiClient NS_DESIGNATED_INITIALIZER;

/// 
/// 
///
/// @param blockhash 
/// 
///  code:200 message:"200 response"
///
/// @return NIMData*
-(NSURLSessionTask*) mopsusBlockBlockhashGetWithBlockhash: (NSString*) blockhash
    completionHandler: (void (^)(NIMData* output, NSError* error)) handler;


/// 
/// 
///
/// @param address 
/// 
///  code:200 message:"200 response"
///
/// @return NIMData*
-(NSURLSessionTask*) mopsusMinedBlocksAddressGetWithAddress: (NSString*) address
    completionHandler: (void (^)(NIMData* output, NSError* error)) handler;


/// 
/// 
///
/// 
///  code:200 message:"200 response"
///
/// @return NIMData*
-(NSURLSessionTask*) mopsusQuickStatsGetWithCompletionHandler: 
    (void (^)(NIMData* output, NSError* error)) handler;


/// 
/// 
///
/// @param transactionhash 
/// 
///  code:200 message:"200 response"
///
/// @return NIMData*
-(NSURLSessionTask*) mopsusTxTransactionhashGetWithTransactionhash: (NSString*) transactionhash
    completionHandler: (void (^)(NIMData* output, NSError* error)) handler;


/// 
/// 
///
/// @param address 
/// 
///  code:200 message:"200 response"
///
/// @return NIMData*
-(NSURLSessionTask*) nimiqxAccountAddressGetWithAddress: (NSString*) address
    completionHandler: (void (^)(NIMData* output, NSError* error)) handler;


/// 
/// 
///
/// @param address 
/// 
///  code:200 message:"200 response"
///
/// @return NIMData*
-(NSURLSessionTask*) nimiqxAccountBlocksAddressGetWithAddress: (NSString*) address
    completionHandler: (void (^)(NIMData* output, NSError* error)) handler;


/// 
/// 
///
/// @param limit 
/// @param address 
/// 
///  code:200 message:"200 response"
///
/// @return NIMData*
-(NSURLSessionTask*) nimiqxAccountBlocksAddressLimitGetWithLimit: (NSNumber*) limit
    address: (NSString*) address
    completionHandler: (void (^)(NIMData* output, NSError* error)) handler;


/// 
/// 
///
/// @param limit 
/// @param skip 
/// @param address 
/// 
///  code:200 message:"200 response"
///
/// @return NIMData*
-(NSURLSessionTask*) nimiqxAccountBlocksAddressLimitSkipGetWithLimit: (NSNumber*) limit
    skip: (NSNumber*) skip
    address: (NSString*) address
    completionHandler: (void (^)(NIMData* output, NSError* error)) handler;


/// 
/// 
///
/// @param address 
/// 
///  code:200 message:"200 response"
///
/// @return NIMData*
-(NSURLSessionTask*) nimiqxAccountTransactionsAddressGetWithAddress: (NSString*) address
    completionHandler: (void (^)(NIMData* output, NSError* error)) handler;


/// 
/// 
///
/// @param limit 
/// @param address 
/// 
///  code:200 message:"200 response"
///
/// @return NIMData*
-(NSURLSessionTask*) nimiqxAccountTransactionsAddressLimitGetWithLimit: (NSNumber*) limit
    address: (NSString*) address
    completionHandler: (void (^)(NIMData* output, NSError* error)) handler;


/// 
/// 
///
/// @param limit 
/// @param skip 
/// @param address 
/// 
///  code:200 message:"200 response"
///
/// @return NIMData*
-(NSURLSessionTask*) nimiqxAccountTransactionsAddressLimitSkipGetWithLimit: (NSNumber*) limit
    skip: (NSNumber*) skip
    address: (NSString*) address
    completionHandler: (void (^)(NIMData* output, NSError* error)) handler;


/// 
/// 
///
/// @param address 
/// 
///  code:200 message:"200 response"
///
/// @return NIMData*
-(NSURLSessionTask*) nimiqxAddressBookAddressGetWithAddress: (NSString*) address
    completionHandler: (void (^)(NIMData* output, NSError* error)) handler;


/// 
/// 
///
/// @param height 
/// 
///  code:200 message:"200 response"
///
/// @return NIMData*
-(NSURLSessionTask*) nimiqxBlockHeightGetWithHeight: (NSNumber*) height
    completionHandler: (void (^)(NIMData* output, NSError* error)) handler;


/// 
/// 
///
/// @param height 
/// 
///  code:200 message:"200 response"
///
/// @return NIMData*
-(NSURLSessionTask*) nimiqxBlockTransactionsHeightGetWithHeight: (NSNumber*) height
    completionHandler: (void (^)(NIMData* output, NSError* error)) handler;


/// 
/// 
///
/// @param limit 
/// @param height 
/// 
///  code:200 message:"200 response"
///
/// @return NIMData*
-(NSURLSessionTask*) nimiqxBlockTransactionsHeightLimitGetWithLimit: (NSNumber*) limit
    height: (NSNumber*) height
    completionHandler: (void (^)(NIMData* output, NSError* error)) handler;


/// 
/// 
///
/// @param limit 
/// @param height 
/// @param skip 
/// 
///  code:200 message:"200 response"
///
/// @return NIMData*
-(NSURLSessionTask*) nimiqxBlockTransactionsHeightLimitSkipGetWithLimit: (NSNumber*) limit
    height: (NSNumber*) height
    skip: (NSNumber*) skip
    completionHandler: (void (^)(NIMData* output, NSError* error)) handler;


/// 
/// 
///
/// @param range 
/// 
///  code:200 message:"200 response"
///
/// @return NIMData*
-(NSURLSessionTask*) nimiqxHashingDistributionRangeGetWithRange: (NSString*) range
    completionHandler: (void (^)(NIMData* output, NSError* error)) handler;


/// 
/// 
///
/// 
///  code:200 message:"200 response"
///
/// @return NIMData*
-(NSURLSessionTask*) nimiqxHashrateDayGetWithCompletionHandler: 
    (void (^)(NIMData* output, NSError* error)) handler;


/// 
/// 
///
/// 
///  code:200 message:"200 response"
///
/// @return NIMData*
-(NSURLSessionTask*) nimiqxHashrateGetWithCompletionHandler: 
    (void (^)(NIMData* output, NSError* error)) handler;


/// 
/// 
///
/// 
///  code:200 message:"200 response"
///
/// @return NIMData*
-(NSURLSessionTask*) nimiqxHashrateHourGetWithCompletionHandler: 
    (void (^)(NIMData* output, NSError* error)) handler;


/// 
/// 
///
/// 
///  code:200 message:"200 response"
///
/// @return NIMData*
-(NSURLSessionTask*) nimiqxHashrateMonthGetWithCompletionHandler: 
    (void (^)(NIMData* output, NSError* error)) handler;


/// 
/// 
///
/// 
///  code:200 message:"200 response"
///
/// @return NIMData*
-(NSURLSessionTask*) nimiqxHashrateWeekGetWithCompletionHandler: 
    (void (^)(NIMData* output, NSError* error)) handler;


/// 
/// 
///
/// 
///  code:200 message:"200 response"
///
/// @return NIMData*
-(NSURLSessionTask*) nimiqxHashrateYearGetWithCompletionHandler: 
    (void (^)(NIMData* output, NSError* error)) handler;


/// 
/// 
///
/// @param label 
/// 
///  code:200 message:"200 response"
///
/// @return NIMData*
-(NSURLSessionTask*) nimiqxLabelBookLabelGetWithLabel: (NSString*) label
    completionHandler: (void (^)(NIMData* output, NSError* error)) handler;


/// 
/// 
///
/// @param limit 
/// 
///  code:200 message:"200 response"
///
/// @return NIMData*
-(NSURLSessionTask*) nimiqxLatestBlocksLimitGetWithLimit: (NSNumber*) limit
    completionHandler: (void (^)(NIMData* output, NSError* error)) handler;


/// 
/// 
///
/// @param limit 
/// @param skip 
/// 
///  code:200 message:"200 response"
///
/// @return NIMData*
-(NSURLSessionTask*) nimiqxLatestBlocksLimitSkipGetWithLimit: (NSNumber*) limit
    skip: (NSNumber*) skip
    completionHandler: (void (^)(NIMData* output, NSError* error)) handler;


/// 
/// 
///
/// @param limit 
/// 
///  code:200 message:"200 response"
///
/// @return NIMData*
-(NSURLSessionTask*) nimiqxLatestTransactionsLimitGetWithLimit: (NSNumber*) limit
    completionHandler: (void (^)(NIMData* output, NSError* error)) handler;


/// 
/// 
///
/// @param limit 
/// @param skip 
/// 
///  code:200 message:"200 response"
///
/// @return NIMData*
-(NSURLSessionTask*) nimiqxLatestTransactionsLimitSkipGetWithLimit: (NSNumber*) limit
    skip: (NSNumber*) skip
    completionHandler: (void (^)(NIMData* output, NSError* error)) handler;


/// 
/// 
///
/// 
///  code:200 message:"200 response"
///
/// @return NIMData*
-(NSURLSessionTask*) nimiqxNetworkStatsGetWithCompletionHandler: 
    (void (^)(NIMData* output, NSError* error)) handler;


/// 
/// 
///
/// 
///  code:200 message:"200 response"
///
/// @return NIMData*
-(NSURLSessionTask*) nimiqxPriceGetWithCompletionHandler: 
    (void (^)(NIMData* output, NSError* error)) handler;


/// 
/// 
///
/// @param address 
/// 
///  code:200 message:"200 response"
///
/// @return NIMData*
-(NSURLSessionTask*) nimiqxSoloMinersRanksAddressGetWithAddress: (NSString*) address
    completionHandler: (void (^)(NIMData* output, NSError* error)) handler;


/// 
/// 
///
/// 
///  code:200 message:"200 response"
///
/// @return NIMData*
-(NSURLSessionTask*) nimiqxSupplyGetWithCompletionHandler: 
    (void (^)(NIMData* output, NSError* error)) handler;


/// 
/// 
///
/// 
///  code:200 message:"200 response"
///
/// @return NIMData*
-(NSURLSessionTask*) nimiqxTop500SoloMinersGetWithCompletionHandler: 
    (void (^)(NIMData* output, NSError* error)) handler;


/// 
/// 
///
/// @param limit 
/// 
///  code:200 message:"200 response"
///
/// @return NIMData*
-(NSURLSessionTask*) nimiqxTop500SoloMinersLimitGetWithLimit: (NSNumber*) limit
    completionHandler: (void (^)(NIMData* output, NSError* error)) handler;


/// 
/// 
///
/// @param limit 
/// @param skip 
/// 
///  code:200 message:"200 response"
///
/// @return NIMData*
-(NSURLSessionTask*) nimiqxTop500SoloMinersLimitSkipGetWithLimit: (NSNumber*) limit
    skip: (NSNumber*) skip
    completionHandler: (void (^)(NIMData* output, NSError* error)) handler;


/// 
/// 
///
/// @param hash 
/// 
///  code:200 message:"200 response"
///
/// @return NIMData*
-(NSURLSessionTask*) nimiqxTransactionHashGetWithHash: (NSString*) hash
    completionHandler: (void (^)(NIMData* output, NSError* error)) handler;


/// 
/// 
///
/// @param range 
/// 
///  code:200 message:"200 response"
///
/// @return NIMData*
-(NSURLSessionTask*) nimiqxTransactionsRangeGetWithRange: (NSString*) range
    completionHandler: (void (^)(NIMData* output, NSError* error)) handler;


/// 
/// 
///
/// 
///  code:200 message:"200 response"
///
/// @return NIMData*
-(NSURLSessionTask*) poolwatchBeeppoolGetWithCompletionHandler: 
    (void (^)(NIMData* output, NSError* error)) handler;


/// 
/// 
///
/// 
///  code:200 message:"200 response"
///
/// @return NIMData*
-(NSURLSessionTask*) poolwatchNimiqpocketGetWithCompletionHandler: 
    (void (^)(NIMData* output, NSError* error)) handler;


/// 
/// 
///
/// 
///  code:200 message:"200 response"
///
/// @return NIMData*
-(NSURLSessionTask*) poolwatchNimiqpoolGetWithCompletionHandler: 
    (void (^)(NIMData* output, NSError* error)) handler;


/// 
/// 
///
/// 
///  code:200 message:"200 response"
///
/// @return NIMData*
-(NSURLSessionTask*) poolwatchNimiqwatchGetWithCompletionHandler: 
    (void (^)(NIMData* output, NSError* error)) handler;


/// 
/// 
///
/// 
///  code:200 message:"200 response"
///
/// @return NIMData*
-(NSURLSessionTask*) poolwatchNimpoolGetWithCompletionHandler: 
    (void (^)(NIMData* output, NSError* error)) handler;


/// 
/// 
///
/// 
///  code:200 message:"200 response"
///
/// @return NIMData*
-(NSURLSessionTask*) poolwatchPoolsGetWithCompletionHandler: 
    (void (^)(NIMData* output, NSError* error)) handler;


/// 
/// 
///
/// @param poolname 
/// 
///  code:200 message:"200 response"
///
/// @return NIMData*
-(NSURLSessionTask*) poolwatchPoolsPoolnameGetWithPoolname: (NSString*) poolname
    completionHandler: (void (^)(NIMData* output, NSError* error)) handler;


/// 
/// 
///
/// @param startdate 
/// @param enddate 
/// @param poolname 
/// 
///  code:200 message:"200 response"
///
/// @return NIMData*
-(NSURLSessionTask*) poolwatchPoolsPoolnameHistoryStartdateEnddateGetWithStartdate: (NSString*) startdate
    enddate: (NSString*) enddate
    poolname: (NSString*) poolname
    completionHandler: (void (^)(NIMData* output, NSError* error)) handler;


/// 
/// 
///
/// 
///  code:200 message:"200 response"
///
/// @return NIMData*
-(NSURLSessionTask*) poolwatchSiriuspoolGetWithCompletionHandler: 
    (void (^)(NIMData* output, NSError* error)) handler;


/// 
/// 
///
/// 
///  code:200 message:"200 response"
///
/// @return NIMData*
-(NSURLSessionTask*) poolwatchSushipoolGetWithCompletionHandler: 
    (void (^)(NIMData* output, NSError* error)) handler;



@end
